### PR TITLE
Add STM32L4 fal_flash port

### PR DESCRIPTION
**Pull request by Spider84**

### CODE REVIEW

**Comment by armink** [comment]
I remember that STM32L4 cannot support reverse order writes. Can you confirm this?

**Comment by Spider84** [comment]
they can write only 64bit at once. And cant rewrite previously wrote double word even if it 0xFF if them already wrote once. Because all double words has crc (64bit+8bit for CRC on each cell of flash).
So! I added check for 0xF....F write and skip this operation to have CRC clean and let availble future write in this cell.
```c
if (write_data != 0xFFFFFFFFFFFFFFFF)
            HAL_FLASH_Program(FLASH_TYPEPROGRAM_DOUBLEWORD, addr, write_data);
```

**Comment by armink** [comment]
OK, thanks a lot. Have you tested whether it works well after the entire database data is filled in 64 bit mode.

**Comment by armink** [comment]
Can you write a loop to increase boot_count?

**Comment by Spider84** [comment]
You right - we have a problem! 👩‍🚀

```[D/FAL] (fal_flash_init:47) Flash device |             stm32_onchip | addr: 0x08000000 | len: 0x00040000 | blk_size: 0x00000800 |initialized finish.
[I/FAL] ==================== FAL partition table ====================
[I/FAL] | name       | flash_dev    |   offset   |    length  |
[I/FAL] -------------------------------------------------------------
[I/FAL] | fdb_device | stm32_onchip | 0x00008000 | 0x00001000 |
[FlashDB] FlashDB V1.2.0 is initialize success.
[FlashDB] You can get the latest version on https://github.com/armink/FlashDB .
Current boot count: 0
Current boot count: 1
Current boot count: 2
Current boot count: 3
Current boot count: 4
Current boot count: 5
Current boot count: 6
Current boot count: 7
Current boot count: 8
Current boot count: 9
Current boot count: 10
Current boot count: 11
Current boot count: 12
Current boot count: 13
Current boot count: 14
Current boot count: 15
Current boot count: 16
Current boot count: 17
Current boot count: 18
Current boot count: 19
Current boot count: 20
Current boot count: 21
[FlashDB][kv][device] (D:/Work/SOS/Firmware/Lib/FlashDB/src/fdb_kvdb.c:1155) Trigger a GC check after created KV.
[FlashDB][kv][device] (D:/Work/SOS/Firmware/Lib/FlashDB/src/fdb_kvdb.c:1051) The remain empty sector is 1, GC threshold is 1.
[E/FAL] (fal_partition_write:470) Partition write error! Flash device(stm32_onchip) write error!
[FlashDB][kv][device] (D:/Work/SOS/Firmware/Lib/FlashDB/src/fdb_kvdb.c:961) Moved the KV (boot_count) from 0x00000778 to 0x00000840.
[FlashDB][kv][device] (D:/Work/SOS/Firmware/Lib/FlashDB/src/fdb_kvdb.c:1031) Collect a sector @0x00000000
Current boot count: 22
[E/FAL] (fal_partition_write:470) Partition write error! Flash device(stm32_onchip) write error!
Current boot count: 22
[E/FAL] (fal_partition_write:470) Partition write error! Flash device(stm32_onchip) write error!
Current boot count: 22
[E/FAL] (fal_partition_write:470) Partition write error! Flash device(stm32_onchip) write error!
```

callback stack of first fail is:
```
fal_partition_write@0x0800f858 (\Firmware\Lib\FlashDB\port\fal\src\fal_partition.c:470)
_fdb_flash_write@0x0800efbc (\Firmware\Lib\FlashDB\src\fdb_utils.c:300)
_fdb_write_status@0x0800eda6 (\Firmware\Lib\FlashDB\src\fdb_utils.c:156)
update_sec_status@0x0800d778 (\Firmware\Lib\FlashDB\src\fdb_kvdb.c:749)
move_kv@0x0800dc42 (\Firmware\Lib\FlashDB\src\fdb_kvdb.c:939)
do_gc@0x0800df78 (\Firmware\Lib\FlashDB\src\fdb_kvdb.c:1025)
sector_iterator@0x0800d84a (\Firmware\Lib\FlashDB\src\fdb_kvdb.c:786)
gc_collect@0x0800e0a2 (\Firmware\Lib\FlashDB\src\fdb_kvdb.c:1053)
set_kv@0x0800e4f0 (\Firmware\Lib\FlashDB\src\fdb_kvdb.c:1220)
fdb_kv_set_blob@0x0800e55c (\Firmware\Lib\FlashDB\src\fdb_kvdb.c:1249)
Init_Task@0x080096b2 (\Firmware\Core\Src\freertos.c:172)
pxPortInitialiseStack@0x0800c550 (\Firmware\Lib\FreeRTOS\portable\GCC\ARM_CM4F\port.c:218)
```

**Comment by armink** [comment]
:+1: Thanks for your contribution.

**Pull request merged**
